apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-apt-caiman
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "46644391235"
    kanikoFlags: --skip-unused-stages --snapshotMode=redo
    project: civic-source-330323
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: thiagolinux
    repository: jx3-quickstart-cluster
  - key: staging
  - key: production
  ingress:
    domain: 34.122.120.138.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    username: my-bot-username
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-tf-jx-apt-caiman-bf8825e32319
  - name: reports
    url: gs://reports-tf-jx-apt-caiman-bf8825e32319
  - name: repository
    url: gs://repository-tf-jx-apt-caiman-bf8825e32319
  vault: {}
  webhook: lighthouse
